-- 코드를 입력하세요
SELECT B.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO as B, (SELECT FOOD_TYPE, MAX(FAVORITES) as max
    FROM REST_INFO
    GROUP BY FOOD_TYPE) as A
WHERE B.FOOD_TYPE = A.FOOD_TYPE and FAVORITES = A.max
ORDER BY B.FOOD_TYPE DESC;